name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t chaisstar/zodiac-parser .
      
    - name: login to docker
      run: docker login -u="${{ secrets.DOCKER_USERNAME}}" -p="${{secrets.DOCKER_PASSWORD}}"
    
    - name: Push the Docker image
      run: docker push chaisstar/zodiac-parser
