// Code generated by "stringer -type=HoroscopeType"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FrenchDefault-0]
	_ = x[FrenchChinese-1]
	_ = x[YahooCommon-2]
	_ = x[AstrolisDetailed-3]
	_ = x[AstrolisLove-4]
}

const _HoroscopeType_name = "FrenchDefaultFrenchChineseYahooCommonAstrolisDetailedAstrolisLove"

var _HoroscopeType_index = [...]uint8{0, 13, 26, 37, 53, 65}

func (i HoroscopeType) String() string {
	if i < 0 || i >= HoroscopeType(len(_HoroscopeType_index)-1) {
		return "HoroscopeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HoroscopeType_name[_HoroscopeType_index[i]:_HoroscopeType_index[i+1]]
}
