// Code generated by "stringer -type=ZodiacSign"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Aries-1]
	_ = x[Taurus-2]
	_ = x[Gemini-3]
	_ = x[Cancer-4]
	_ = x[Leo-5]
	_ = x[Virgo-6]
	_ = x[Libra-7]
	_ = x[Scorpio-8]
	_ = x[Sagittarius-9]
	_ = x[Capricorn-10]
	_ = x[Aquarius-11]
	_ = x[Pisces-12]
}

const _ZodiacSign_name = "AriesTaurusGeminiCancerLeoVirgoLibraScorpioSagittariusCapricornAquariusPisces"

var _ZodiacSign_index = [...]uint8{0, 5, 11, 17, 23, 26, 31, 36, 43, 54, 63, 71, 77}

func (i ZodiacSign) String() string {
	i -= 1
	if i < 0 || i >= ZodiacSign(len(_ZodiacSign_index)-1) {
		return "ZodiacSign(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ZodiacSign_name[_ZodiacSign_index[i]:_ZodiacSign_index[i+1]]
}
